import '../../shared/widgets/review_source_badge.dart';
import '../../shared/widgets/source_badge.dart';
import 'place.dart';
import 'review.dart';

final mockOfficialPlaces = [
  Place(
    id: 'p1',
    name: 'Gwangjang Market',
    category: 'Street Food',
    district: 'Jongno-gu',
    rating: 4.5,
    jeongRating: 4.7,
    externalRating: 4.4,
    reviewCount: 342,
    jeongReviewCount: 38,
    externalReviewCount: 304,
    sourceType: SourceType.official,
    distance: '1.2 km',
    description: 'Must-visit traditional market',
    address: '88 Changgyeonggung-ro, Jongno-gu, Seoul',
    phone: '02-2267-0291',
    openingHours: 'Open · Closes at 10:00 PM',
    tags: ['Traditional', 'Budget-friendly', 'Street Food'],
    tips: [
      ForeignerTip(icon: 'menu_book', text: 'English menu available at some stalls'),
      ForeignerTip(icon: 'credit_card', text: 'Cash preferred at most stalls'),
      ForeignerTip(icon: 'translate', text: 'Limited English spoken'),
    ],
  ),
  Place(
    id: 'p2',
    name: 'Tosokchon Samgyetang',
    category: 'Korean',
    district: 'Jongno-gu',
    rating: 4.3,
    jeongRating: 4.6,
    externalRating: 4.2,
    reviewCount: 218,
    jeongReviewCount: 23,
    externalReviewCount: 195,
    sourceType: SourceType.official,
    distance: '2.1 km',
    description: 'Famous ginseng chicken soup',
    address: '5 Jahamun-ro 5-gil, Jongno-gu, Seoul',
    phone: '02-737-7444',
    openingHours: 'Open · Closes at 9:00 PM',
    tags: ['Traditional', 'Must-visit', 'Healthy'],
    tips: [
      ForeignerTip(icon: 'menu_book', text: 'English menu available'),
      ForeignerTip(icon: 'credit_card', text: 'Card payment accepted'),
      ForeignerTip(icon: 'schedule', text: 'Expect 30min+ wait during peak hours'),
    ],
  ),
  Place(
    id: 'p3',
    name: 'Bukchon Hanok Village',
    category: 'Attraction',
    district: 'Jongno-gu',
    rating: 4.4,
    jeongRating: 4.5,
    externalRating: 4.3,
    reviewCount: 567,
    jeongReviewCount: 67,
    externalReviewCount: 500,
    sourceType: SourceType.official,
    distance: '1.8 km',
    description: 'Beautiful traditional Korean houses',
    address: '37 Gyedong-gil, Jongno-gu, Seoul',
    openingHours: 'Open 24 hours (quiet hours 10PM-8AM)',
    tags: ['Culture', 'Photography', 'Walking'],
    tips: [
      ForeignerTip(icon: 'volume_off', text: 'Please be quiet - residential area'),
      ForeignerTip(icon: 'photo_camera', text: 'Best photo spots at viewpoint #5 and #6'),
      ForeignerTip(icon: 'directions_walk', text: 'Wear comfortable shoes - steep hills'),
    ],
  ),
  Place(
    id: 'p4',
    name: 'Myeongdong Kyoja',
    category: 'Korean',
    district: 'Jung-gu',
    rating: 4.2,
    jeongRating: 4.4,
    externalRating: 4.1,
    reviewCount: 456,
    jeongReviewCount: 45,
    externalReviewCount: 411,
    sourceType: SourceType.official,
    distance: '0.8 km',
    description: 'Best kalguksu in Seoul',
    address: '29 Myeongdong 10-gil, Jung-gu, Seoul',
    phone: '02-776-5348',
    openingHours: 'Open · Closes at 9:30 PM',
    tags: ['Noodles', 'Budget-friendly', 'Must-visit'],
    tips: [
      ForeignerTip(icon: 'menu_book', text: 'Photo menu available'),
      ForeignerTip(icon: 'credit_card', text: 'Cash only'),
      ForeignerTip(icon: 'translate', text: 'Basic English spoken'),
    ],
  ),
  Place(
    id: 'p5',
    name: 'Namsan Seoul Tower',
    category: 'Attraction',
    district: 'Yongsan-gu',
    rating: 4.6,
    jeongRating: 4.8,
    externalRating: 4.5,
    reviewCount: 892,
    jeongReviewCount: 112,
    externalReviewCount: 780,
    sourceType: SourceType.official,
    distance: '3.5 km',
    description: 'Iconic Seoul landmark with panoramic views',
    address: '105 Namsangongwon-gil, Yongsan-gu, Seoul',
    phone: '02-3455-9277',
    openingHours: 'Open · Closes at 11:00 PM',
    tags: ['Landmark', 'Views', 'Date spot'],
    tips: [
      ForeignerTip(icon: 'credit_card', text: 'Card payment accepted'),
      ForeignerTip(icon: 'schedule', text: 'Visit at sunset for best views'),
      ForeignerTip(icon: 'directions_bus', text: 'Take cable car or bus #02'),
    ],
  ),
];

final mockCommunityPlaces = [
  Place(
    id: 'c1',
    name: 'Hidden Tteokbokki Spot',
    category: 'Street Food',
    district: 'Mapo-gu',
    rating: 4.8,
    jeongRating: 4.8,
    reviewCount: 12,
    jeongReviewCount: 12,
    externalReviewCount: 0,
    sourceType: SourceType.community,
    distance: '3.2 km',
    description: '0% tourists, 100% flavor',
    registeredBy: '@traveler_mike',
    address: 'Near Mangwon Station Exit 2',
    openingHours: 'Open · Closes at 8:00 PM',
    tags: ['Hidden gem', 'Spicy', 'Budget-friendly'],
    tips: [
      ForeignerTip(icon: 'translate', text: 'No English spoken - use translator app'),
      ForeignerTip(icon: 'credit_card', text: 'Cash only'),
      ForeignerTip(icon: 'local_fire_department', text: 'Ask for mild if you cannot handle spicy'),
    ],
  ),
  Place(
    id: 'c2',
    name: 'Rooftop Cafe with Han River View',
    category: 'Cafe',
    district: 'Yongsan-gu',
    rating: 4.7,
    jeongRating: 4.7,
    reviewCount: 8,
    jeongReviewCount: 8,
    externalReviewCount: 0,
    sourceType: SourceType.community,
    distance: '4.5 km',
    description: 'Best sunset spot in Seoul',
    registeredBy: '@sarah_adventures',
    address: 'Near Ichon Station Exit 4',
    openingHours: 'Open · Closes at 10:00 PM',
    tags: ['Views', 'Date spot', 'Instagram'],
    tips: [
      ForeignerTip(icon: 'menu_book', text: 'English menu available'),
      ForeignerTip(icon: 'credit_card', text: 'Card payment accepted'),
      ForeignerTip(icon: 'schedule', text: 'Reserve in advance for rooftop seats'),
    ],
  ),
  Place(
    id: 'c3',
    name: 'Grandma\'s Kimbap',
    category: 'Korean',
    district: 'Seongdong-gu',
    rating: 4.9,
    jeongRating: 4.9,
    reviewCount: 6,
    jeongReviewCount: 6,
    externalReviewCount: 0,
    sourceType: SourceType.community,
    distance: '2.8 km',
    description: 'Homemade kimbap, feels like Korean grandma made it',
    registeredBy: '@berlin_backpacker',
    address: 'Near Wangsimni Station Exit 7',
    tags: ['Homestyle', 'Budget-friendly', 'Comfort food'],
    tips: [
      ForeignerTip(icon: 'schedule', text: 'Opens early 6AM - great for breakfast'),
      ForeignerTip(icon: 'credit_card', text: 'Cash preferred'),
    ],
  ),
];

final mockReviews = [
  Review(
    id: 'r1',
    placeId: 'p1',
    source: ReviewSourceType.jeong,
    authorName: '@sarah_adventures',
    nationality: '🇺🇸',
    rating: 5.0,
    date: '2026.03.08',
    content:
        'Best Korean BBQ experience! The staff helped us grill and the prices were very reasonable. Must visit!',
    likes: 12,
    comments: 3,
    hasPhotos: true,
  ),
  Review(
    id: 'r2',
    placeId: 'p1',
    source: ReviewSourceType.naver,
    authorName: 'Naver User',
    rating: 4.0,
    date: '2026.02.15',
    content: '직장인 회식 장소로 자주 갑니다. 고기 퀄리티가 좋고 가성비 최고',
    translatedContent:
        'I often come here for company dinners. The meat quality is great and it\'s very affordable.',
    likes: 8,
    comments: 1,
  ),
  Review(
    id: 'r3',
    placeId: 'p1',
    source: ReviewSourceType.jeong,
    authorName: '@tokyo_foodie',
    nationality: '🇯🇵',
    rating: 4.5,
    date: '2026.03.01',
    content:
        'Amazing atmosphere! The traditional Korean setting made the meal even more special. Highly recommend the bulgogi.',
    likes: 7,
    comments: 2,
    hasPhotos: true,
  ),
  Review(
    id: 'r4',
    placeId: 'p1',
    source: ReviewSourceType.naver,
    authorName: 'Naver User',
    rating: 5.0,
    date: '2026.01.28',
    content: '분위기 좋고 직원분들도 친절해요. 외국인 친구 데려갔는데 아주 만족했어요.',
    translatedContent:
        'Great atmosphere and friendly staff. Brought my foreign friend here and they were very satisfied.',
    likes: 15,
    comments: 4,
  ),
  Review(
    id: 'r5',
    placeId: 'p2',
    source: ReviewSourceType.jeong,
    authorName: '@london_eats',
    nationality: '🇬🇧',
    rating: 4.5,
    date: '2026.03.05',
    content:
        'The samgyetang here is incredible. Waited 40 minutes but totally worth it. Get the abalone version!',
    likes: 9,
    comments: 1,
    hasPhotos: true,
  ),
  Review(
    id: 'r6',
    placeId: 'p3',
    source: ReviewSourceType.jeong,
    authorName: '@paris_wanderer',
    nationality: '🇫🇷',
    rating: 4.0,
    date: '2026.02.20',
    content:
        'Beautiful village but very crowded on weekends. Go early morning for the best experience. The narrow alleys are charming.',
    likes: 14,
    comments: 5,
    hasPhotos: true,
  ),
];

List<Review> getReviewsForPlace(String placeId) {
  return mockReviews.where((r) => r.placeId == placeId).toList();
}

List<Place> get allMockPlaces => [...mockOfficialPlaces, ...mockCommunityPlaces];
