version: "3.8"

services:
  api:
    build: .
    ports:
      - "3000:8080"
    env_file:
      - .env
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    restart: unless-stopped
