// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRzcjWwYg9gC7eICd46ZV2B0sxTdQBpgE',
    appId: '1:1040428184607:web:73410bcb625ed7fe4b112a',
    messagingSenderId: '1040428184607',
    projectId: 'jeong-7ef84',
    authDomain: 'jeong-7ef84.firebaseapp.com',
    storageBucket: 'jeong-7ef84.firebasestorage.app',
    measurementId: 'G-9WNLVYR5VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCofrzqD9xwUc_KBStO2-2brzE1Hq0amKU',
    appId: '1:1040428184607:android:3395d6b4e925cfac4b112a',
    messagingSenderId: '1040428184607',
    projectId: 'jeong-7ef84',
    storageBucket: 'jeong-7ef84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnbFVUxzjH_F-9EN793TGIWouJJJow0BQ',
    appId: '1:1040428184607:ios:200abd6e1dd66c614b112a',
    messagingSenderId: '1040428184607',
    projectId: 'jeong-7ef84',
    storageBucket: 'jeong-7ef84.firebasestorage.app',
    iosBundleId: 'com.jeong.jeong',
  );
}
